#注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
#网关名称
spring:
  application:
    name: service-zuul
#配置网关反向代理    
zuul:
  #定义转发服务的规则(路由规则)
  routes:
    api-a:   # api-a这里可以随便命名
      #以 /api-member/开头的接口请求转发到会员服务
      path: /api-member/**
      #serviceId是会员服务别名
      serviceId: app-member
      #问题：如果会员服务做了集群，如何转发? zuul网关默认整合了ribbon，自动失效负载均衡轮询效果！
    api-b:
      #客户端请求以127.0.0.1:80/api-order/开头的接口请求转发到订单服务
      path: /api-order/**
      #订单服务别名
      serviceId: app-order