############################  搭建动态网关时使用  ##########################
#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
#网关名称
spring:
  application:
    name: service-zuul
  # zuul动态网关从git上读取配置文件的版本
  # git配置文件地址：https://gitee.com/liuch890228/distributed_profile_learning/blob/master/configtest/service-zuul-dev.yml
  cloud:
    config:
    #读取的版本，通过后缀确定是开发环境or测试环境or生产环境
      profile: dev
      discovery:
        #读取config-server在注册中心上注册的别名
        service-id: config-server
        #开启读取权限
        enabled: true
        
# zuul动态网关-开启监控中心所有端口
management:  
  endpoints:
    web:  
      exposure: 
        include: "*"