server: 
  port: 8006
spring:
  application:
    name: app-pay
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka  
    #把自己注册到注册中心
    register-with-eureka: true
    # 从eureka上获取注册服务列表
    fetch-registry: true
ribbon:
  # 不设置超时时间，调用会员服务1.5s延时的接口时会报 redaTimeOut 错误
  # 建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间 
  ConnectionTimeout: 5000