# 服务端口号
server:
  port: 8501
#服务别名
spring:
  application:
    name: consul-member
  # consul注册中心地址
  cloud:
    consul:
      host: localhost
      #consul端口号
      port: 8500
      discovery:
      #默认情况下服务注册到注册中心上的的address是随机生成的，修改hostname为本机ip
        hostname: 192.168.5.102