server:
  port: 9100

# 定义eureka集群时，需要定义集群服务名称，各节点的名称定义要一致
spring:
  application:
    name: app-eureka-cluster
eureka:
  instance:
  #注册中心ip地址
    hostname: 127.0.0.1
    #注册到服务注册中心的实例显示的是ip
    prefer-ip-address: true
  client:
    service-url:
      # server9100注册到8100上 
      defaultZone: http://127.0.0.1:8100/eureka
    # 搭建eureka集群时，需要将自己注册到注册中心 
    register-with-eureka: true
    fetch-registry: true
    