# 会员服务项目端口号
server:
  port: 8000
# 服务别名--服务注册到注册中心的名称
spring:
  application:
    name: app-member
eureka:
  client:
    service-url:
      #将当前服务注册到eureka注册中心
      defaultZone: http://localhost:8100/eureka/,http://localhost:9100/eureka/
    # 将自己注册到注册中心，设置为true
    register-with-eureka: true
    # 检索服务信息
    fetch-registry: true
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）  
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2  